builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  asmflags:
  - all=-trimpath={{.Env.GOPATH}}
  ldflags:
  - all=-trimpath={{.Env.GOPATH}}
  - -s -w -X main.VERSION={{ .Tag }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Arch }}'
  homepage:  https://github.com/hbagdi/hupit
  description: Watch files and reload configuration
  maintainer: Harry Bagdi <harrybagdi@gmail.com>
  license: Apache License v2.0
  formats:
  - deb
  - rpm
